### ISSUE TITLE
Cannot export Archimate model to an empty MS SQL DB

### ISSUE THREAD

**Issue by paszewczyk** [archi-contribs/database-plugin#36]
Please see the screenshots for examples.
Archie 4.2.
![2018-05-14_17h26_44](https://user-images.githubusercontent.com/39260616/40007093-343f95be-579c-11e8-80fb-d0688044804c.png)
![2018-05-14_17h27_35](https://user-images.githubusercontent.com/39260616/40007080-2face740-579c-11e8-8ec6-150c2cb30467.png)

**Comment by paszewczyk** [comment]
Hi Hevre,
Please find attached the trace.
I’m using the following SQL Server version:
Microsoft SQL Server Developer (64-bit) - 12.0.5207.0

Pozdrawiam / Best regards,

Paweł Szewczyk

**Comment by herve91** [comment]
I do not see the trace file ... As it is text, you may copy and past the last lines here on github ...

ps: I edited your last post to hide your email address ...

**Comment by paszewczyk** [comment]
Hi,
The last command (failed) in the SQL Server log is the following
SQL:BatchCompleted	**DROP TABLE IF EXISTS dbo.database_version** 	Microsoft JDBC Driver for SQL Server		Archie	0	0	0	0		53	2018-05-15 09:03:07.777	2018-05-15 09:03:07.777		1 - Error	
![2018-05-15_09h29_38](https://user-images.githubusercontent.com/39260616/40042678-80b42faa-5822-11e8-9eee-ef3f13310668.png)

**Comment by herve91** [comment]
In fact, your screenshot does not help me ... The "DROP TABLE IF EXISTS dbo.database_version" request is executed in case of a rollback when an exception occurs and I need this exception ...

The easiest way for me to investigate is to have a copy of the log file that is generated when the plugin is switched in trace mode (this can be done on the plugin's preference page, on the logger tab).

**Comment by paszewczyk** [comment]
Please see attached the entire DatabasePlugin.log
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/2004233/DatabasePlugin.log)

Your help is greatly appreciated!

**Comment by herve91** [comment]
My apologies, but your log file is not in trace mode and does not contain the information I need ...

![trace mode](https://user-images.githubusercontent.com/9281982/40048887-9e56c9b2-5833-11e8-8311-9f7f20945f91.png)

**Comment by paszewczyk** [comment]
OK!
 I didn't see these buttons, as I always enable "Expert" mode ;-).
Please see the attached log:

[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/2004262/DatabasePlugin.log)

**Comment by herve91** [comment]
Thanks ...

Unfortunately, I still do not have the information I was hopping for ... I thought I would have an error message before the CREATE TABLE and the rollback ...
```
2018-05-15 11:34:55 TRACE 1230:DBDatabaseConnection           - CREATE TABLE dbo.database_version (archi_plugin varchar(50) NOT NULL, version int NOT NULL)
2018-05-15 11:34:55 DEBUG 1379:DBDatabaseConnection           - Rollbacking database transaction.
```

Nevertheless, I will investigate and solve it as quick as I can.

**Comment by herve91** [comment]
I've rewritten the SQL requests and it should work now. I also updated the error message to be more explicit in case it doesn't work either on your environment.

Please let me know.

**Comment by paszewczyk** [comment]
Hi,
I’ll test it today.
Thanks!

Pozdrawiam / Best regards,

Paweł Szewczyk

**Comment by paszewczyk** [comment]
Hi,
I did a test with the newer version of the plugin on MS SQL.
Please see the attached log and a simple Archimate model that I used for this test
Results:


1.       DB upgrade does not work

2.       DB creation works.

3.       DB export works

4.       DB import does not work.

5.       How to use DB<> model comparison? I made a change (added a note to the diagram and associated it with an application, but it was not detected)

Pozdrawiam / Best regards,

Paweł Szewczyk


________________________________
Pomyśl o środowisku, zanim wydrukujesz ten e-mail.

Credit Agricole Bank Polska S.A. z siedzibą we Wrocławiu przy pl. Orląt Lwowskich 1. Wpisana do Krajowego Rejestru Sądowego - Rejestru Przedsiębiorców pod numerem KRS: 00000 39887. Sąd rejestrowy: Sąd Rejonowy dla Wrocławia - Fabryczna, VI Wydział Gospodarczy Krajowego Rejestru Sądowego. Kapitał zakładowy w wysokości: 782 333 400,00 ZŁ, w całości wpłacony. NIP: 657-008-22-74. Wiadomość ta oraz wszelkie załączone do niej dokumenty są tajemnicą nadawcy i mogą podlegać ochronie prawnej. Jeżeli jest Pan/Pani niezamierzonym adresatem tej wiadomości, prosimy o poinformowanie o tym fakcie nadawcy oraz o jej niezwłoczne usunięcie. Jednocześnie informujemy, iż w razie niezamierzonego otrzymania tej wiadomości nie może Pan/Pani jej ujawniać, kopiować oraz wykorzystywać.
________________________________
Please consider the environment before printing this e-mail.

Credit Agricole Bank Polska S.A. having its registered office in Wrocław at Pl. Orląt Lwowskich 1. Entered into the National Court Register - the Registry of Entrepreneurs under number KRS:00000 39887. Registry Court: District Court for Wrocław - Fabryczna, VI Commercial Division of the National Court Register. The share capital of PLN 782 333 400.00, fully paid. NIP tax identification number: 657-008-22-74. This email and any attached files are confidential and may be legally privileged. If you have received this transmission in error please notify the sender immediately and then delete this email. If you are not the intended recipient, any disclosure, reproduction, copying, distribution or other dissemination or use of this communication is strictly prohibited.
________________________________

**Comment by herve91** [comment]
Hi,

I just release the beta 4 version that should solve your issue (thanks to the logfile you sent me).

I rushed to deliver this release, and did not test all the functionalities on all the databases, so please do not hesitate to stress test it and drop me a line if you discover misbehaviours :)

**Comment by paszewczyk** [comment]
Hi Herve,
It seems that certain issues still remain.
I’ve sent the log to your private e-mail.

Pozdrawiam / Best regards,

Paweł Szewczyk
